import { tableName } from './table-names';

export const DB_NAME = 'todo_list_db';
export const DB_VERSION = 1;

export const version1: string[] = [
  `CREATE TABLE IF NOT EXISTS ${tableName.currency} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS ${tableName.rate} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    amount INTEGER NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS ${tableName.generation} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    libelle TEXT NOT NULL
  );`,
  `CREATE TABLE IF NOT EXISTS ${tableName.card} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    srcPicture TEXT NOT NULL,
    averagePrice INTEGER NULL,
    isPriority BOOLEAN NOT NULL,
    serieID INTEGER NOT NULL,
    generationID INTEGER NOT NULL,
    picture TEXT NOT NULL,
    FOREIGN KEY(serieID) REFERENCES ${tableName.serie}(id),
    FOREIGN KEY(generationID) REFERENCES ${tableName.generation}(id)
  );`,
  `CREATE TABLE IF NOT EXISTS ${tableName.serie} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    srcLogo TEXT NOT NULL
  );`,
  `INSERT INTO ${tableName.generation} (libelle) VALUES
    ('Génération 1 - Kanto'),
    ('Génération 2 - Johto'),
    ('Génération 3 - Hoenn'),
    ('Génération 4 - Sinnoh'),
    ('Génération 5 - Unys'),
    ('Génération 6 - Kalos'),
    ('Génération 7 - Alola'),
    ('Génération 8 - Galar'),
    ('Génération 9 - Paldea')
  `,
  `INSERT INTO ${tableName.serie} (name, srcLogo) VALUES
    -- Génération 1 - Kanto
    ('Base Set',                    'assets/images/tcg-logos/base1.png'),
    ('Jungle',                      'assets/images/tcg-logos/base2.png'),
    ('Fossil',                      'assets/images/tcg-logos/base3.png'),
    ('Base Set 2',                  'assets/images/tcg-logos/base4.png'),
    ('Team Rocket',                 'assets/images/tcg-logos/base5.png'),
    ('Gym Heroes',                  'assets/images/tcg-logos/gym1.png'),
    ('Gym Challenge',               'assets/images/tcg-logos/gym2.png'),
    ('Legendary Collection',        'assets/images/tcg-logos/base6.png'),
    ('Wizards Black Star Promos',   'assets/images/tcg-logos/basep.png'),
    -- Génération 2 - Johto
    ('Neo Genesis',                 'assets/images/tcg-logos/neo1.png'),
    ('Neo Discovery',               'assets/images/tcg-logos/neo2.png'),
    ('Neo Revelation',              'assets/images/tcg-logos/neo3.png'),
    ('Neo Destiny',                 'assets/images/tcg-logos/neo4.png'),
    ('Expedition Base Set',         'assets/images/tcg-logos/ecard1.png'),
    ('Aquapolis',                   'assets/images/tcg-logos/ecard2.png'),
    ('Skyridge',                    'assets/images/tcg-logos/ecard3.png'),
    -- Génération 3 - Hoenn
    ('EX Ruby & Sapphire',          'assets/images/tcg-logos/ex1.png'),
    ('EX Sandstorm',                'assets/images/tcg-logos/ex2.png'),
    ('EX Dragon',                   'assets/images/tcg-logos/ex3.png'),
    ('EX Team Magma vs Team Aqua',  'assets/images/tcg-logos/ex4.png'),
    ('EX Hidden Legends',           'assets/images/tcg-logos/ex5.png'),
    ('EX FireRed & LeafGreen',      'assets/images/tcg-logos/ex6.png'),
    ('EX Team Rocket Returns',      'assets/images/tcg-logos/ex7.png'),
    ('EX Deoxys',                   'assets/images/tcg-logos/ex8.png'),
    ('EX Emerald',                  'assets/images/tcg-logos/ex9.png'),
    ('EX Unseen Forces',            'assets/images/tcg-logos/ex10.png'),
    ('EX Delta Species',            'assets/images/tcg-logos/ex11.png'),
    ('EX Legend Maker',             'assets/images/tcg-logos/ex12.png'),
    ('EX Holon Phantoms',           'assets/images/tcg-logos/ex13.png'),
    ('EX Crystal Guardians',        'assets/images/tcg-logos/ex14.png'),
    ('EX Dragon Frontiers',         'assets/images/tcg-logos/ex15.png'),
    ('EX Power Keepers',            'assets/images/tcg-logos/ex16.png'),
    ('POP Series 1',                'assets/images/tcg-logos/pop1.png'),
    ('POP Series 2',                'assets/images/tcg-logos/pop2.png'),
    ('POP Series 3',                'assets/images/tcg-logos/pop3.png'),
    ('POP Series 4',                'assets/images/tcg-logos/pop4.png'),
    ('POP Series 5',                'assets/images/tcg-logos/pop5.png'),
    -- Génération 4 - Sinnoh
    ('Diamond & Pearl',             'assets/images/tcg-logos/dp1.png'),
    ('Mysterious Treasures',        'assets/images/tcg-logos/dp2.png'),
    ('Secret Wonders',              'assets/images/tcg-logos/dp3.png'),
    ('Great Encounters',            'assets/images/tcg-logos/dp4.png'),
    ('Majestic Dawn',               'assets/images/tcg-logos/dp5.png'),
    ('Legends Awakened',            'assets/images/tcg-logos/dp6.png'),
    ('Stormfront',                  'assets/images/tcg-logos/dp7.png'),
    ('DP Black Star Promos',        'assets/images/tcg-logos/dpp.png'),
    ('Platinum',                    'assets/images/tcg-logos/pl1.png'),
    ('Rising Rivals',               'assets/images/tcg-logos/pl2.png'),
    ('Supreme Victors',             'assets/images/tcg-logos/pl3.png'),
    ('Arceus',                      'assets/images/tcg-logos/pl4.png'),
    ('POP Series 6',                'assets/images/tcg-logos/pop6.png'),
    ('POP Series 7',                'assets/images/tcg-logos/pop7.png'),
    ('POP Series 8',                'assets/images/tcg-logos/pop8.png'),
    ('POP Series 9',                'assets/images/tcg-logos/pop9.png'),
    ('HeartGold & SoulSilver',      'assets/images/tcg-logos/hgss1.png'),
    ('Unleashed',                   'assets/images/tcg-logos/hgss2.png'),
    ('Undaunted',                   'assets/images/tcg-logos/hgss3.png'),
    ('Triumphant',                  'assets/images/tcg-logos/hgss4.png'),
    ('HS Black Star Promos',        'assets/images/tcg-logos/hsp.png'),
    ('Call of Legends',             'assets/images/tcg-logos/col1.png'),
    -- Génération 5 - Unys
    ('Black & White',               'assets/images/tcg-logos/bw1.png'),
    ('Emerging Powers',             'assets/images/tcg-logos/bw2.png'),
    ('Noble Victories',             'assets/images/tcg-logos/bw3.png'),
    ('Next Destinies',              'assets/images/tcg-logos/bw4.png'),
    ('Dark Explorers',              'assets/images/tcg-logos/bw5.png'),
    ('Dragons Exalted',             'assets/images/tcg-logos/bw6.png'),
    ('Dragon Vault',                'assets/images/tcg-logos/dv1.png'),
    ('Boundaries Crossed',          'assets/images/tcg-logos/bw7.png'),
    ('Plasma Storm',                'assets/images/tcg-logos/bw8.png'),
    ('Plasma Freeze',               'assets/images/tcg-logos/bw9.png'),
    ('Plasma Blast',                'assets/images/tcg-logos/bw10.png'),
    ('Legendary Treasures',         'assets/images/tcg-logos/bw11.png'),
    ('BW Black Star Promos',        'assets/images/tcg-logos/bwp.png'),
    -- Génération 6 - Kalos
    ('Kalos Starter Set',           'assets/images/tcg-logos/xy0.png'),
    ('XY',                          'assets/images/tcg-logos/xy1.png'),
    ('Flashfire',                   'assets/images/tcg-logos/xy2.png'),
    ('Furious Fists',               'assets/images/tcg-logos/xy3.png'),
    ('Phantom Forces',              'assets/images/tcg-logos/xy4.png'),
    ('Primal Clash',                'assets/images/tcg-logos/xy5.png'),
    ('Double Crisis',               'assets/images/tcg-logos/dc1.png'),
    ('Roaring Skies',               'assets/images/tcg-logos/xy6.png'),
    ('Ancient Origins',             'assets/images/tcg-logos/xy7.png'),
    ('BREAKthrough',                'assets/images/tcg-logos/xy8.png'),
    ('BREAKpoint',                  'assets/images/tcg-logos/xy9.png'),
    ('Generations',                 'assets/images/tcg-logos/g1.png'),
    ('Fates Collide',               'assets/images/tcg-logos/xy10.png'),
    ('Steam Siege',                 'assets/images/tcg-logos/xy11.png'),
    ('Evolutions',                  'assets/images/tcg-logos/xy12.png'),
    ('XY Black Star Promos',        'assets/images/tcg-logos/xyp.png'),
    -- Génération 7 - Alola
    ('Sun & Moon',                  'assets/images/tcg-logos/sm1.png'),
    ('Guardians Rising',            'assets/images/tcg-logos/sm2.png'),
    ('Burning Shadows',             'assets/images/tcg-logos/sm3.png'),
    ('Shining Legends',             'assets/images/tcg-logos/sm35.png'),
    ('Crimson Invasion',            'assets/images/tcg-logos/sm4.png'),
    ('Ultra Prism',                 'assets/images/tcg-logos/sm5.png'),
    ('Forbidden Light',             'assets/images/tcg-logos/sm6.png'),
    ('Celestial Storm',             'assets/images/tcg-logos/sm7.png'),
    ('Dragon Majesty',              'assets/images/tcg-logos/sm75.png'),
    ('Lost Thunder',                'assets/images/tcg-logos/sm8.png'),
    ('Team Up',                     'assets/images/tcg-logos/sm9.png'),
    ('Unbroken Bonds',              'assets/images/tcg-logos/sm10.png'),
    ('Unified Minds',               'assets/images/tcg-logos/sm11.png'),
    ('Hidden Fates',                'assets/images/tcg-logos/sm115.png'),
    ('Cosmic Eclipse',              'assets/images/tcg-logos/sm12.png'),
    ('SM Black Star Promos',        'assets/images/tcg-logos/smp.png'),
    ('Detective Pikachu',           'assets/images/tcg-logos/det1.png'),
    -- Génération 8 - Galar
    ('Sword & Shield',              'assets/images/tcg-logos/swsh1.png'),
    ('Rebel Clash',                 'assets/images/tcg-logos/swsh2.png'),
    ('Darkness Ablaze',             'assets/images/tcg-logos/swsh3.png'),
    ('Champion''s Path',            'assets/images/tcg-logos/swsh35.png'),
    ('Vivid Voltage',               'assets/images/tcg-logos/swsh4.png'),
    ('Shining Fates',               'assets/images/tcg-logos/swsh45.png'),
    ('Battle Styles',               'assets/images/tcg-logos/swsh5.png'),
    ('Chilling Reign',              'assets/images/tcg-logos/swsh6.png'),
    ('Evolving Skies',              'assets/images/tcg-logos/swsh7.png'),
    ('Fusion Strike',               'assets/images/tcg-logos/swsh8.png'),
    ('Brilliant Stars',             'assets/images/tcg-logos/swsh9.png'),
    ('Astral Radiance',             'assets/images/tcg-logos/swsh10.png'),
    ('Pokémon GO',                  'assets/images/tcg-logos/pgo.png'),
    ('Lost Origin',                 'assets/images/tcg-logos/swsh11.png'),
    ('Silver Tempest',              'assets/images/tcg-logos/swsh12.png'),
    ('Crown Zenith',                'assets/images/tcg-logos/swsh12pt5.png'),
    ('SWSH Black Star Promos',      'assets/images/tcg-logos/swshp.png'),
    -- Génération 9 - Paldea
    ('Scarlet & Violet',            'assets/images/tcg-logos/sv1.png'),
    ('Paldea Evolved',              'assets/images/tcg-logos/sv2.png'),
    ('Obsidian Flames',             'assets/images/tcg-logos/sv3.png'),
    ('151',                         'assets/images/tcg-logos/sv3pt5.png'),
    ('Paradox Rift',                'assets/images/tcg-logos/sv4.png'),
    ('Paldean Fates',               'assets/images/tcg-logos/sv4pt5.png'),
    ('Temporal Forces',             'assets/images/tcg-logos/sv5.png'),
    ('Twilight Masquerade',         'assets/images/tcg-logos/sv6.png'),
    ('Shrouded Fable',              'assets/images/tcg-logos/sv6pt5.png'),
    ('Stellar Crown',               'assets/images/tcg-logos/sv7.png'),
    ('Surging Sparks',              'assets/images/tcg-logos/sv8.png'),
    ('Prismatic Evolutions',        'assets/images/tcg-logos/sv8pt5.png'),
    ('Journey Together',            'assets/images/tcg-logos/sv9.png'),
    ('SV Black Star Promos',        'assets/images/tcg-logos/svp.png')
  `,
];

export const DB_UPGRADES = [{ toVersion: DB_VERSION, statements: version1 }];
