import { Card } from '../models/Card';
import { Generation } from '../models/Generation';
import { Serie } from '../models/Serie';

export const MOCK_GENERATIONS: Generation[] = [
    { id: 1, libelle: 'Génération 1 - Kanto' },
    { id: 2, libelle: 'Génération 2 - Johto' },
    { id: 3, libelle: 'Génération 3 - Hoenn' },
    { id: 4, libelle: 'Génération 4 - Sinnoh' },
    { id: 5, libelle: 'Génération 5 - Unys' },
    { id: 6, libelle: 'Génération 6 - Kalos' },
    { id: 7, libelle: 'Génération 7 - Alola' },
    { id: 8, libelle: 'Génération 8 - Galar' },
    { id: 9, libelle: 'Génération 9 - Paldea' },
];

export const MOCK_SERIES: Serie[] = [
    // Génération 1 - Kanto
    { id: 1,   name: 'Base Set',                   srcLogo: 'assets/images/tcg-logos/base1.png' },
    { id: 2,   name: 'Jungle',                     srcLogo: 'assets/images/tcg-logos/base2.png' },
    { id: 3,   name: 'Fossil',                     srcLogo: 'assets/images/tcg-logos/base3.png' },
    { id: 4,   name: 'Base Set 2',                 srcLogo: 'assets/images/tcg-logos/base4.png' },
    { id: 5,   name: 'Team Rocket',                srcLogo: 'assets/images/tcg-logos/base5.png' },
    { id: 6,   name: 'Gym Heroes',                 srcLogo: 'assets/images/tcg-logos/gym1.png' },
    { id: 7,   name: 'Gym Challenge',              srcLogo: 'assets/images/tcg-logos/gym2.png' },
    { id: 8,   name: 'Legendary Collection',       srcLogo: 'assets/images/tcg-logos/base6.png' },
    { id: 9,   name: 'Wizards Black Star Promos',  srcLogo: 'assets/images/tcg-logos/basep.png' },
    // Génération 2 - Johto
    { id: 10,  name: 'Neo Genesis',                srcLogo: 'assets/images/tcg-logos/neo1.png' },
    { id: 11,  name: 'Neo Discovery',              srcLogo: 'assets/images/tcg-logos/neo2.png' },
    { id: 12,  name: 'Neo Revelation',             srcLogo: 'assets/images/tcg-logos/neo3.png' },
    { id: 13,  name: 'Neo Destiny',                srcLogo: 'assets/images/tcg-logos/neo4.png' },
    { id: 14,  name: 'Expedition Base Set',        srcLogo: 'assets/images/tcg-logos/ecard1.png' },
    { id: 15,  name: 'Aquapolis',                  srcLogo: 'assets/images/tcg-logos/ecard2.png' },
    { id: 16,  name: 'Skyridge',                   srcLogo: 'assets/images/tcg-logos/ecard3.png' },
    // Génération 3 - Hoenn
    { id: 17,  name: 'EX Ruby & Sapphire',         srcLogo: 'assets/images/tcg-logos/ex1.png' },
    { id: 18,  name: 'EX Sandstorm',               srcLogo: 'assets/images/tcg-logos/ex2.png' },
    { id: 19,  name: 'EX Dragon',                  srcLogo: 'assets/images/tcg-logos/ex3.png' },
    { id: 20,  name: 'EX Team Magma vs Team Aqua', srcLogo: 'assets/images/tcg-logos/ex4.png' },
    { id: 21,  name: 'EX Hidden Legends',          srcLogo: 'assets/images/tcg-logos/ex5.png' },
    { id: 22,  name: 'EX FireRed & LeafGreen',     srcLogo: 'assets/images/tcg-logos/ex6.png' },
    { id: 23,  name: 'EX Team Rocket Returns',     srcLogo: 'assets/images/tcg-logos/ex7.png' },
    { id: 24,  name: 'EX Deoxys',                  srcLogo: 'assets/images/tcg-logos/ex8.png' },
    { id: 25,  name: 'EX Emerald',                 srcLogo: 'assets/images/tcg-logos/ex9.png' },
    { id: 26,  name: 'EX Unseen Forces',           srcLogo: 'assets/images/tcg-logos/ex10.png' },
    { id: 27,  name: 'EX Delta Species',           srcLogo: 'assets/images/tcg-logos/ex11.png' },
    { id: 28,  name: 'EX Legend Maker',            srcLogo: 'assets/images/tcg-logos/ex12.png' },
    { id: 29,  name: 'EX Holon Phantoms',          srcLogo: 'assets/images/tcg-logos/ex13.png' },
    { id: 30,  name: 'EX Crystal Guardians',       srcLogo: 'assets/images/tcg-logos/ex14.png' },
    { id: 31,  name: 'EX Dragon Frontiers',        srcLogo: 'assets/images/tcg-logos/ex15.png' },
    { id: 32,  name: 'EX Power Keepers',           srcLogo: 'assets/images/tcg-logos/ex16.png' },
    { id: 33,  name: 'POP Series 1',               srcLogo: 'assets/images/tcg-logos/pop1.png' },
    { id: 34,  name: 'POP Series 2',               srcLogo: 'assets/images/tcg-logos/pop2.png' },
    { id: 35,  name: 'POP Series 3',               srcLogo: 'assets/images/tcg-logos/pop3.png' },
    { id: 36,  name: 'POP Series 4',               srcLogo: 'assets/images/tcg-logos/pop4.png' },
    { id: 37,  name: 'POP Series 5',               srcLogo: 'assets/images/tcg-logos/pop5.png' },
    // Génération 4 - Sinnoh
    { id: 38,  name: 'Diamond & Pearl',            srcLogo: 'assets/images/tcg-logos/dp1.png' },
    { id: 39,  name: 'Mysterious Treasures',       srcLogo: 'assets/images/tcg-logos/dp2.png' },
    { id: 40,  name: 'Secret Wonders',             srcLogo: 'assets/images/tcg-logos/dp3.png' },
    { id: 41,  name: 'Great Encounters',           srcLogo: 'assets/images/tcg-logos/dp4.png' },
    { id: 42,  name: 'Majestic Dawn',              srcLogo: 'assets/images/tcg-logos/dp5.png' },
    { id: 43,  name: 'Legends Awakened',           srcLogo: 'assets/images/tcg-logos/dp6.png' },
    { id: 44,  name: 'Stormfront',                 srcLogo: 'assets/images/tcg-logos/dp7.png' },
    { id: 45,  name: 'DP Black Star Promos',       srcLogo: 'assets/images/tcg-logos/dpp.png' },
    { id: 46,  name: 'Platinum',                   srcLogo: 'assets/images/tcg-logos/pl1.png' },
    { id: 47,  name: 'Rising Rivals',              srcLogo: 'assets/images/tcg-logos/pl2.png' },
    { id: 48,  name: 'Supreme Victors',            srcLogo: 'assets/images/tcg-logos/pl3.png' },
    { id: 49,  name: 'Arceus',                     srcLogo: 'assets/images/tcg-logos/pl4.png' },
    { id: 50,  name: 'POP Series 6',               srcLogo: 'assets/images/tcg-logos/pop6.png' },
    { id: 51,  name: 'POP Series 7',               srcLogo: 'assets/images/tcg-logos/pop7.png' },
    { id: 52,  name: 'POP Series 8',               srcLogo: 'assets/images/tcg-logos/pop8.png' },
    { id: 53,  name: 'POP Series 9',               srcLogo: 'assets/images/tcg-logos/pop9.png' },
    { id: 54,  name: 'HeartGold & SoulSilver',     srcLogo: 'assets/images/tcg-logos/hgss1.png' },
    { id: 55,  name: 'Unleashed',                  srcLogo: 'assets/images/tcg-logos/hgss2.png' },
    { id: 56,  name: 'Undaunted',                  srcLogo: 'assets/images/tcg-logos/hgss3.png' },
    { id: 57,  name: 'Triumphant',                 srcLogo: 'assets/images/tcg-logos/hgss4.png' },
    { id: 58,  name: 'HS Black Star Promos',       srcLogo: 'assets/images/tcg-logos/hsp.png' },
    { id: 59,  name: 'Call of Legends',            srcLogo: 'assets/images/tcg-logos/col1.png' },
    // Génération 5 - Unys
    { id: 60,  name: 'Black & White',              srcLogo: 'assets/images/tcg-logos/bw1.png' },
    { id: 61,  name: 'Emerging Powers',            srcLogo: 'assets/images/tcg-logos/bw2.png' },
    { id: 62,  name: 'Noble Victories',            srcLogo: 'assets/images/tcg-logos/bw3.png' },
    { id: 63,  name: 'Next Destinies',             srcLogo: 'assets/images/tcg-logos/bw4.png' },
    { id: 64,  name: 'Dark Explorers',             srcLogo: 'assets/images/tcg-logos/bw5.png' },
    { id: 65,  name: 'Dragons Exalted',            srcLogo: 'assets/images/tcg-logos/bw6.png' },
    { id: 66,  name: 'Dragon Vault',               srcLogo: 'assets/images/tcg-logos/dv1.png' },
    { id: 67,  name: 'Boundaries Crossed',         srcLogo: 'assets/images/tcg-logos/bw7.png' },
    { id: 68,  name: 'Plasma Storm',               srcLogo: 'assets/images/tcg-logos/bw8.png' },
    { id: 69,  name: 'Plasma Freeze',              srcLogo: 'assets/images/tcg-logos/bw9.png' },
    { id: 70,  name: 'Plasma Blast',               srcLogo: 'assets/images/tcg-logos/bw10.png' },
    { id: 71,  name: 'Legendary Treasures',        srcLogo: 'assets/images/tcg-logos/bw11.png' },
    { id: 72,  name: 'BW Black Star Promos',       srcLogo: 'assets/images/tcg-logos/bwp.png' },
    // Génération 6 - Kalos
    { id: 73,  name: 'Kalos Starter Set',          srcLogo: 'assets/images/tcg-logos/xy0.png' },
    { id: 74,  name: 'XY',                         srcLogo: 'assets/images/tcg-logos/xy1.png' },
    { id: 75,  name: 'Flashfire',                  srcLogo: 'assets/images/tcg-logos/xy2.png' },
    { id: 76,  name: 'Furious Fists',              srcLogo: 'assets/images/tcg-logos/xy3.png' },
    { id: 77,  name: 'Phantom Forces',             srcLogo: 'assets/images/tcg-logos/xy4.png' },
    { id: 78,  name: 'Primal Clash',               srcLogo: 'assets/images/tcg-logos/xy5.png' },
    { id: 79,  name: 'Double Crisis',              srcLogo: 'assets/images/tcg-logos/dc1.png' },
    { id: 80,  name: 'Roaring Skies',              srcLogo: 'assets/images/tcg-logos/xy6.png' },
    { id: 81,  name: 'Ancient Origins',            srcLogo: 'assets/images/tcg-logos/xy7.png' },
    { id: 82,  name: 'BREAKthrough',               srcLogo: 'assets/images/tcg-logos/xy8.png' },
    { id: 83,  name: 'BREAKpoint',                 srcLogo: 'assets/images/tcg-logos/xy9.png' },
    { id: 84,  name: 'Generations',                srcLogo: 'assets/images/tcg-logos/g1.png' },
    { id: 85,  name: 'Fates Collide',              srcLogo: 'assets/images/tcg-logos/xy10.png' },
    { id: 86,  name: 'Steam Siege',                srcLogo: 'assets/images/tcg-logos/xy11.png' },
    { id: 87,  name: 'Evolutions',                 srcLogo: 'assets/images/tcg-logos/xy12.png' },
    { id: 88,  name: 'XY Black Star Promos',       srcLogo: 'assets/images/tcg-logos/xyp.png' },
    // Génération 7 - Alola
    { id: 89,  name: 'Sun & Moon',                 srcLogo: 'assets/images/tcg-logos/sm1.png' },
    { id: 90,  name: 'Guardians Rising',           srcLogo: 'assets/images/tcg-logos/sm2.png' },
    { id: 91,  name: 'Burning Shadows',            srcLogo: 'assets/images/tcg-logos/sm3.png' },
    { id: 92,  name: 'Shining Legends',            srcLogo: 'assets/images/tcg-logos/sm35.png' },
    { id: 93,  name: 'Crimson Invasion',           srcLogo: 'assets/images/tcg-logos/sm4.png' },
    { id: 94,  name: 'Ultra Prism',                srcLogo: 'assets/images/tcg-logos/sm5.png' },
    { id: 95,  name: 'Forbidden Light',            srcLogo: 'assets/images/tcg-logos/sm6.png' },
    { id: 96,  name: 'Celestial Storm',            srcLogo: 'assets/images/tcg-logos/sm7.png' },
    { id: 97,  name: 'Dragon Majesty',             srcLogo: 'assets/images/tcg-logos/sm75.png' },
    { id: 98,  name: 'Lost Thunder',               srcLogo: 'assets/images/tcg-logos/sm8.png' },
    { id: 99,  name: 'Team Up',                    srcLogo: 'assets/images/tcg-logos/sm9.png' },
    { id: 100, name: 'Unbroken Bonds',             srcLogo: 'assets/images/tcg-logos/sm10.png' },
    { id: 101, name: 'Unified Minds',              srcLogo: 'assets/images/tcg-logos/sm11.png' },
    { id: 102, name: 'Hidden Fates',               srcLogo: 'assets/images/tcg-logos/sm115.png' },
    { id: 103, name: 'Cosmic Eclipse',             srcLogo: 'assets/images/tcg-logos/sm12.png' },
    { id: 104, name: 'SM Black Star Promos',       srcLogo: 'assets/images/tcg-logos/smp.png' },
    { id: 105, name: 'Detective Pikachu',          srcLogo: 'assets/images/tcg-logos/det1.png' },
    // Génération 8 - Galar
    { id: 106, name: 'Sword & Shield',             srcLogo: 'assets/images/tcg-logos/swsh1.png' },
    { id: 107, name: 'Rebel Clash',                srcLogo: 'assets/images/tcg-logos/swsh2.png' },
    { id: 108, name: 'Darkness Ablaze',            srcLogo: 'assets/images/tcg-logos/swsh3.png' },
    { id: 109, name: "Champion's Path",            srcLogo: 'assets/images/tcg-logos/swsh35.png' },
    { id: 110, name: 'Vivid Voltage',              srcLogo: 'assets/images/tcg-logos/swsh4.png' },
    { id: 111, name: 'Shining Fates',              srcLogo: 'assets/images/tcg-logos/swsh45.png' },
    { id: 112, name: 'Battle Styles',              srcLogo: 'assets/images/tcg-logos/swsh5.png' },
    { id: 113, name: 'Chilling Reign',             srcLogo: 'assets/images/tcg-logos/swsh6.png' },
    { id: 114, name: 'Evolving Skies',             srcLogo: 'assets/images/tcg-logos/swsh7.png' },
    { id: 115, name: 'Fusion Strike',              srcLogo: 'assets/images/tcg-logos/swsh8.png' },
    { id: 116, name: 'Brilliant Stars',            srcLogo: 'assets/images/tcg-logos/swsh9.png' },
    { id: 117, name: 'Astral Radiance',            srcLogo: 'assets/images/tcg-logos/swsh10.png' },
    { id: 118, name: 'Pokémon GO',                 srcLogo: 'assets/images/tcg-logos/pgo.png' },
    { id: 119, name: 'Lost Origin',                srcLogo: 'assets/images/tcg-logos/swsh11.png' },
    { id: 120, name: 'Silver Tempest',             srcLogo: 'assets/images/tcg-logos/swsh12.png' },
    { id: 121, name: 'Crown Zenith',               srcLogo: 'assets/images/tcg-logos/swsh12pt5.png' },
    { id: 122, name: 'SWSH Black Star Promos',     srcLogo: 'assets/images/tcg-logos/swshp.png' },
    // Génération 9 - Paldea
    { id: 123, name: 'Scarlet & Violet',           srcLogo: 'assets/images/tcg-logos/sv1.png' },
    { id: 124, name: 'Paldea Evolved',             srcLogo: 'assets/images/tcg-logos/sv2.png' },
    { id: 125, name: 'Obsidian Flames',            srcLogo: 'assets/images/tcg-logos/sv3.png' },
    { id: 126, name: '151',                        srcLogo: 'assets/images/tcg-logos/sv3pt5.png' },
    { id: 127, name: 'Paradox Rift',               srcLogo: 'assets/images/tcg-logos/sv4.png' },
    { id: 128, name: 'Paldean Fates',              srcLogo: 'assets/images/tcg-logos/sv4pt5.png' },
    { id: 129, name: 'Temporal Forces',            srcLogo: 'assets/images/tcg-logos/sv5.png' },
    { id: 130, name: 'Twilight Masquerade',        srcLogo: 'assets/images/tcg-logos/sv6.png' },
    { id: 131, name: 'Shrouded Fable',             srcLogo: 'assets/images/tcg-logos/sv6pt5.png' },
    { id: 132, name: 'Stellar Crown',              srcLogo: 'assets/images/tcg-logos/sv7.png' },
    { id: 133, name: 'Surging Sparks',             srcLogo: 'assets/images/tcg-logos/sv8.png' },
    { id: 134, name: 'Prismatic Evolutions',       srcLogo: 'assets/images/tcg-logos/sv8pt5.png' },
    { id: 135, name: 'Journey Together',           srcLogo: 'assets/images/tcg-logos/sv9.png' },
    { id: 136, name: 'SV Black Star Promos',       srcLogo: 'assets/images/tcg-logos/svp.png' },
];

export const MOCK_CARDS: Card[] = [
    { id: 1, name: 'Pikachu',    srcPicture: 'assets/card_empty.png', averagePrice: 5,   isPriority: true,  serieID: 1,  serie: MOCK_SERIES[0],  generationID: 1, generation: MOCK_GENERATIONS[0] },
    { id: 2, name: 'Dracaufeu', srcPicture: 'assets/card_empty.png', averagePrice: 150, isPriority: true,  serieID: 1,  serie: MOCK_SERIES[0],  generationID: 1, generation: MOCK_GENERATIONS[0] },
    { id: 3, name: 'Mewtwo',    srcPicture: 'assets/card_empty.png', averagePrice: 80,  isPriority: false, serieID: 1,  serie: MOCK_SERIES[0],  generationID: 1, generation: MOCK_GENERATIONS[0] },
    { id: 4, name: 'Lugia',     srcPicture: 'assets/card_empty.png', averagePrice: 60,  isPriority: false, serieID: 10, serie: MOCK_SERIES[9],  generationID: 2, generation: MOCK_GENERATIONS[1] },
    { id: 5, name: 'Amphinobi', srcPicture: 'assets/card_empty.png', averagePrice: 25,  isPriority: false, serieID: 74, serie: MOCK_SERIES[73], generationID: 6, generation: MOCK_GENERATIONS[5] },
    { id: 6, name: 'Rayquaza',  srcPicture: 'assets/card_empty.png', averagePrice: 120, isPriority: true,  serieID: 17, serie: MOCK_SERIES[16], generationID: 3, generation: MOCK_GENERATIONS[2] },
];
